coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: unit
      paths:
        - api/
      statuses:
        - type: project
          target: 50%
          threshold: 1%
    - name: integration
      paths:
        - api/
      statuses:
        - type: project
          target: auto
          threshold: 1%
