name: API workflow

on: [push, pull_request]

jobs:
  first:
    runs-on: ubuntu-latest
    name: One commit
    steps:
      - uses: actions/checkout@v4
      - name: Fetch base
        run: git fetch origin main --depth=1000
      - name: log
        run: git log --oneline
      - name: show head
        run: git show HEAD
      - name: show fetch head
        run: git show FETCH_HEAD
      - name: diff
        run: git diff -U0 FETCH_HEAD...
  second:
    runs-on: ubuntu-latest
    name: All commits
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch base
        run: git fetch origin main --depth=1000
      - name: log
        run: git log --oneline
      - name: show head
        run: git show HEAD
      - name: show fetch head
        run: git show FETCH_HEAD
      - name: diff
        run: git diff -U0 FETCH_HEAD...
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.10"
      # - name: Install requirements
      #   run: pip install -r api/requirements.txt
      # - name: Run unit tests and collect coverage
      #   run: pytest --cov --cov-report="xml:unit.coverage.xml" api/**/tests/unit
      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@v5
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     files: unit.coverage.xml
      #     flags: unit
      # - name: Run integration tests and collect coverage
      #   run: pytest --cov --cov-report="xml:integration.coverage.xml" api/**/tests/integration
      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@v5
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     files: integration.coverage.xml
      #     flags: integration
